---
- name: Check if Rust is already installed
  ansible.builtin.stat:
    path: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin/rustup"
  register: rust_installed

- name: Install Rust
  ansible.builtin.shell: |
    set -o pipefail
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y -q
  args:
    executable: /bin/bash
  changed_when: true
  when: not rust_installed.stat.exists

- name: Get Rust version
  ansible.builtin.command:
    argv:
      - "{{ ansible_facts['env']['HOME'] }}/.cargo/bin/rustc"
      - --version
  register: rust_version
  changed_when: false

- name: Set Rust facts
  ansible.builtin.set_fact:
    rust:
      version: "{{ rust_version.stdout.split()[1] }}"

- name: Install Rust packages
  community.general.cargo:
    name: "{{ item }}"
    state: latest
    executable: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin/cargo"
  loop:
    - just
    - cargo-prosa
    - ripgrep
...
