---
# ansible-pull -U https://github.com/reneca/reneca.git dev.yml
# ansible-playbook -c local -i localhost, dev.yml
- name: Playbook for personnal development
  hosts: localhost
  roles:
    - role: system

    - role: rust

    - role: vscode
      when: >
        has_gui is defined and has_gui == true

    - role: gcp

    - role: ollama
    - role: lmstudio

    # Install Zed except for a WSL
    - role: zed
      when: >
        has_gui is defined and has_gui == true

    # Install and configure Claude code only if a GCP Vertex project is available or Ollama is locally install
    - role: claude
      when: >
        (lmstudio is defined and lmstudio.host is defined)
        or ollama.host is defined
        or gcloud.core.project is defined

  tasks:
    - name: Playbook facts
      ansible.builtin.debug:
        msg: "{{ item.value }}"
      loop:
        - {name: "GUI", value: "{{ has_gui | default(omit) }}", when: "{{ has_gui is defined }}"}
        - {name: "Rust", value: "{{ {'version': rust.version} }}", when: "{{ rust.version is defined }}"}
        - {name: "GCloud", value: "{{ gcloud }}", when: "{{ gcloud.core is defined and gcloud.core | length > 0 }}"}
        - {name: "Ollama", value: "{{ ollama }}", when: "{{ ollama.version is defined }}"}
        - {name: "LMStudio", value: "{{ lmstudio | default(omit) }}", when: "{{ lmstudio is defined and lmstudio | length > 0 }}"}
      loop_control:
        label: "{{ item.name }}"
      when: item.when | bool
...