---
- name: Check if zed is already install
  command: which zed
  register: zed_installed
  ignore_errors: true
  changed_when: false

- name: Install Zed
  shell: curl -f https://zed.dev/install.sh | sh
  args:
    executable: /bin/bash
  when:
    - zed_installed.rc != 0
    - ansible_facts['os_family'] != "Darwin"
    - '"microsoft" not in ansible_facts["kernel"]'

- name: Install Zed vith Homebrew (macOS)
  ansible.builtin.homebrew_cask:
    name: zed
    state: present
  when:
    - zed_installed.rc != 0
    - ansible_facts['os_family'] == "Darwin"

- name: Get Zed version
  ansible.builtin.shell: >
    zed -v | cut -d' ' -f2
  register: zed_version
  changed_when: false
  when: zed_installed.rc == 0 or ansible_facts['os_family'] == "Darwin" or "microsoft" not in ansible_facts["kernel"]

- name: Set Zed facts
  ansible.builtin.set_fact:
    zed: >-
      {{
        zed | combine({
          'version': zed_version.stdout,
          'config_dir': lookup('env', 'XDG_CONFIG_HOME') | default(ansible_facts['env'].HOME + '/.config', true) + '/zed'
        })
      }}
  when:
    - zed_installed.rc == 0 or ansible_facts['os_family'] == "Darwin" or "microsoft" not in ansible_facts["kernel"]
    - zed_version.rc == 0

- name: Add LMStudio or Ollama agent provider
  ansible.builtin.set_fact:
    zed: >-
      {{
        zed | combine({
          'settings': zed.settings | combine(
            {
              'disable_ai': false,
              'agent_ui_font_size': 14.0,
              'agent': {
                'default_model': {
                  'provider': 'ollama' if (ollama is defined and ollama.host is defined) else 'lmstudio',
                  'model': 'qwen3-coder-next:q8_0' if (ansible_facts['memtotal_mb'] > 90000) else 'qwen3-coder'
                }
              },
              'edit_predictions': {
                'provider': 'ollama' if (ollama is defined and ollama.host is defined) else 'none'
              },
              'language_models': (
                {
                  'ollama': {
                    'api_url': ollama.host,
                    'auto_discover': true,
                  }
                } if (ollama is defined and ollama.host is defined) else
                {
                  'lmstudio': {
                    'api_url': lmstudio.host + '/api/v1'
                  }
                }
              )
            },
            recursive=true
          ),
          'keymap': zed.keymap + [{
              'context': '!ContextEditor > (Editor && mode == full)',
              'bindings':
              {
                'cmd-k': 'assistant::InlineAssist'
              }
            }]
        })
      }}
  when:
    - zed.version is defined
    - (ollama is defined and ollama.host is defined) or (lmstudio is defined and lmstudio.host is defined)

- name: Check if Zed configuration folder exist (after first launch)
  ansible.builtin.stat:
    path: "{{ zed.config_dir }}"
  register: zed_config_dir_stat
  when: zed.config_dir is defined

- name: Create Zed configuration files from defaults
  ansible.builtin.copy:
    mode: "0644"
    dest: "{{ zed.config_dir }}/{{ item.key }}.json"
    content: "{{ item.value | to_nice_json(indent=2) }}"
  loop:
    - { key: "settings", value: "{{ zed.settings }}" }
    - { key: "keymap", value: "{{ zed.keymap }}" }
  when:
    - zed.config_dir is defined
    - zed_config_dir_stat.stat.exists
    - zed_config_dir_stat.stat.isdir
...
