---
- name: Check if Claude Code is already install
  ansible.builtin.stat:
    path: ~/.local/bin/claude
  register: claude_installed
- name: Install Claude Code
  ansible.builtin.shell: |
    curl -fsSL https://claude.ai/install.sh | bash
  args:
    executable: /bin/bash
  when: not claude_installed.stat.exists

- name: Check if Claude need an API Key helper to generate an API Key
  ansible.builtin.stat:
    path: ~/.claude/api-key-gen.sh
  register: api_key_gen_stat

- name: Define Claude Code settings facts
  ansible.builtin.set_fact:
    claude_code:
      api_key_helper: "{{ api_key_gen_stat.stat.exists and api_key_gen_stat.stat.executable }}"
      base_url: >-
        {% if lookup('ansible.builtin.env', 'ANTHROPIC_BASE_URL', default='') != '' -%}
          {{ lookup('ansible.builtin.env', 'ANTHROPIC_BASE_URL') }}
        {%- elif lmstudio.host is defined -%}
          {{ lmstudio.host }}
        {%- elif ollama.host is defined -%}
          {{ ollama.host }}
        {%- elif lookup('ansible.builtin.env', 'OPENROUTER_API_KEY', default='') != '' -%}
          https://openrouter.ai/api
        {%- else -%}
          undefined
        {%- endif %}
      auth_token: >-
        {% if lmstudio.host is defined -%}
          lmstudio
        {%- elif ollama.host is defined -%}
          ollama
        {%- elif lookup('ansible.builtin.env', 'OPENROUTER_API_KEY', default='') != '' -%}
          {{ lookup('ansible.builtin.env', 'OPENROUTER_API_KEY') }}
        {%- else -%}
          undefined
        {%- endif %}
      model: >-
        {% if lmstudio.host is defined -%}
          qwen/qwen3-coder-next
        {%- elif ollama.host is defined -%}
          {%- if ollama.version is not defined or ansible_facts['memtotal_mb'] > 90000 -%}
            qwen3-coder-next:q8_0
          {%- else -%}
            qwen3-coder
          {%- endif -%}
        {%- elif lookup('ansible.builtin.env', 'OPENROUTER_API_KEY', default='') != '' -%}
          qwen/qwen3.6-plus:free
        {%- else -%}
          claude-opus-4-6
        {%- endif -%}

- name: Claude Code settings
  template:
    mode: "0640"
    src: "templates/settings.j2"
    dest: "~/.claude/settings.json"

- name: Claude Code Status Line script
  template:
    mode: "0750"
    src: "templates/statusline.j2"
    dest: "~/.claude/statusline.py"
